//sync actions
export const SET_QUERY = "SET_QUERY";
export const SET_IS_SEARCHING = 'SET_IS_SEARCHING';

//async actions
export const FETCH_RESULTS_REQUEST = "FETCH_RESULTS_REQUEST";
export const FETCH_RESULTS_SUCCESS = "FETCH_RESULTS_SUCCESS";
export const FETCH_RESULTS_FAILURE = "FETCH_RESULTS_FAILURE";

export const PATCH_RESULTS_REQUEST = "PATCH_RESULTS_REQUEST";
export const PATCH_RESULTS_SUCCESS = "PATCH_RESULTS_SUCCESS";
export const PATCH_RESULTS_FAILURE = "PATCH_RESULTS_FAILURE";